databases:
  - name: inuno.ai
    plan: free
    databaseName: inuno_ai
    user: omofon

services:
  - type: web
    plan: free
    name: inuno
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inuno.ai
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
